


my_violins = function(xName = NA,
                      yName,
                      hline = NA,
                      xlab = NA,
                      ylab,
                      yTicks = NA,
                      prefix = NA,
                      write = TRUE,
                      # by default, use all scenarios:
                      .agg = agg ) {
  
  # # test only
  # xName = "true.effect.dist"
  # yName = "PhatRelBias"
  # hline = 0
  # xlab = "Distribution"
  # ylab = "Relative bias in estimated percentage above q"
  # yTicks = seq(0, 5, 1)
  # # ylab = bquote( hat(P)[q] ~ "relative bias" )
  # # ylab = quote( hat(P)[>q] )
  # # ylab = quote(lambda[>{q}])
  # # quote(lambda[>{x}])
  # # quote(P[50 > {q}])
  
  #browser()
  

  .agg$Y = .agg[[yName]]
  
  #browser()
  
  # stratified plot (along x-axis)
  if ( !is.na(xName) ) {
    .agg$X = as.factor( .agg[[xName]] )
    string = paste( "plot_", xName, "_vs_", yName, ".pdf", sep = "" )
    
    p = ggplot( data = .agg,
                aes(x = X,
                    y = Y) ) +
      
      geom_violin(fill = "orange",
                  alpha = 0.4) +
      
      theme_classic() +
      
      theme(axis.title.x = element_text(size=16),
            axis.title.y = element_text(size = 14),
            axis.text.x = element_text(size=14),
            axis.text.y = element_text(size=14)) + 
      
      xlab(xlab)
      
  } 
  
  # marginal plot (no x-axis)
  if ( is.na(xName) ) {
    
    string = paste( "plot_marginal_", yName, ".pdf", sep = "" )
    
    p = ggplot( data = .agg,
                aes(x = as.factor(1),
                    y = Y) ) +
      
      geom_violin(fill = "orange",
                  alpha = 0.4) +
      
      theme_classic() +
      
      theme(axis.title.x=element_blank(),
            axis.text.x=element_blank(),
            axis.ticks.x=element_blank(),
            
            axis.title.y = element_text(size = 14),
            axis.text.y = element_text(size=14))
  }
  

    p  = p + geom_boxplot(width=0.1, fill = "white", outlier.shape = NA) +
    scale_fill_brewer(palette="RdBu") +
    ylab(ylab)
  
  if ( !is.na(hline) ) p = p + geom_hline(yintercept = hline,
                                          lty = 2,
                                          color = "gray")
  
  if ( any( !is.na(yTicks) ) ) p = p + scale_y_continuous( breaks = yTicks,
                                                           limits = c( min(yTicks), max(yTicks) ) )
  
 
  # save to local directory and Overleaf
  if ( write == TRUE ) {

    if ( !is.na(prefix) ) string = paste( prefix, string, sep = "_" )
    my_ggsave( name = string,
               .width = 8,
               .height = 5)
  } else {
    p
  }

}




my_ggsave = function(name,
                     .width,
                     .height,
                     .results.dir = figures.results.dir,
                     .overleaf.dir = overleaf.dir) {
  
  for ( dir in c(.results.dir, .overleaf.dir) ) {
    setwd(dir)
    ggsave( name,
            width = .width, 
            height = .height,
            device = "pdf" )
  }
}


overleaf_figure_strings = function() {
  setwd(figures.results.dir)
  
  for ( f in list.files() ){
    
    cat( "\\begin{figure}[H] \\centering \\includegraphics[width=110mm]{supp_figures_autogenerated/",
         f,
         "} \\end{figure}",
         sep = "" )
    
    cat("\n\n")
    
  }
}

